import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "node:path";

export default defineConfig({
  plugins: [react()],
  resolve: { alias: { "@": path.resolve(__dirname, "./src") } },
  test: {
    include: ["src/**/*.test.{ts,tsx}"],
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/app/**",
        "src/**/*.d.ts",
        "src/proxy.ts",
        "src/components/shells/app-shell.tsx",
        "src/components/shells/auth-shell.tsx",
        "src/lib/supabase/**",
        "src/modules/admin/infrastructure/**",
        "src/modules/analytics/infrastructure/**",
        "src/modules/identity/application/auth-actions.ts",
        "src/modules/identity/application/checkpoint-actions.ts",
        "src/modules/identity/application/form-state.ts",
        "src/modules/identity/infrastructure/identity-dal.ts",
        "src/modules/identity/infrastructure/progress-client.ts",
        "src/modules/identity/infrastructure/progress-dal.ts",
        "src/modules/identity/infrastructure/rate-limit.ts",
        "src/modules/identity/ui/**",
        "src/modules/discovery/application/discovery-actions.ts",
        "src/modules/discovery/infrastructure/discovery-dal.ts",
        "src/modules/discovery/ui/**",
        "src/modules/connect/application/connect-actions.ts",
        "src/modules/connect/infrastructure/**",
        "src/modules/connect/ui/**",
        "src/modules/builder-network/application/**",
        "src/modules/builder-network/infrastructure/**",
        "src/modules/builder-network/ui/**",
        "src/modules/collaboration/application/**",
        "src/modules/collaboration/infrastructure/**",
        "src/modules/collaboration/ui/**",
        "src/modules/capability-verification/application/**",
        "src/modules/capability-verification/infrastructure/**",
        "src/modules/capability-verification/ui/**",
        "src/modules/institution/application/**",
        "src/modules/institution/infrastructure/**",
        "src/modules/institution/ui/**",
        "src/modules/builder-guide/application/builder-guide-actions.ts",
        "src/modules/builder-guide/infrastructure/**",
        "src/modules/economic-pathways/application/economic-pathway-actions.ts",
        "src/modules/economic-pathways/infrastructure/**",
        "src/modules/economic-pathways/ui/**",
        "src/modules/human-potential/application/profile-actions.ts",
        "src/modules/human-potential/infrastructure/**",
        "src/modules/human-potential/ui/**",
        "src/modules/living-builder-profile/application/**",
        "src/modules/living-builder-profile/infrastructure/**",
        "src/modules/living-builder-profile/ui/**",
        "src/modules/mission/application/mission-actions.ts",
        "src/modules/mission/infrastructure/**",
        "src/modules/mission/ui/**",
        "src/modules/journey/application/journey-actions.ts",
        "src/modules/journey/infrastructure/**",
        "src/modules/journey/ui/**",
        "src/modules/quest/application/quest-actions.ts",
        "src/modules/quest/infrastructure/**",
        "src/modules/quest/ui/**",
        "src/modules/project/application/project-actions.ts",
        "src/modules/project/infrastructure/**",
        "src/modules/project/ui/**",
        "src/modules/portfolio/application/portfolio-actions.ts",
        "src/modules/portfolio/infrastructure/**",
        "src/modules/portfolio/ui/**",
        "src/modules/opportunities/application/**",
        "src/modules/opportunities/infrastructure/**",
      ],
      thresholds: { lines: 80, functions: 80, branches: 75, statements: 80 },
    },
  },
});
